# Generated by Django 3.0.4 on 2023-06-13 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expence',
            old_name='name',
            new_name='title',
        ),
    ]
