# Generated by Django 3.0.4 on 2023-06-13 11:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20230613_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expence',
            name='amount_currency',
        ),
        migrations.RemoveField(
            model_name='income',
            name='amount_currency',
        ),
        migrations.AlterField(
            model_name='expence',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
